'use server';

import { revalidatePath } from 'next/cache';
import { redirect } from 'next/navigation';
import z from 'zod';

import { neon } from '@neondatabase/serverless';

const FormSchema = z.object({
  id: z.string(),
  customerId: z.string(),
  amount: z.coerce.number(), // coerce 是强制转换为数字的意思，因为 formData.get 返回的是字符串
  status: z.enum(['pending', 'paid']),
  date: z.string(),
});

/**
 * This is the schema for creating a new invoice.
 * It omits the id and date fields because they are generated by the database.
 */
const CreateInvoice = FormSchema.omit({ id: true, date: true });

const sql = neon(process.env.DATABASE_URL!);

export async function createInvoice(formData: FormData) {
  const { customerId, amount, status } = CreateInvoice.parse({
    customerId: formData.get('customerId'),
    amount: formData.get('amount'),
    status: formData.get('status'),
  });

  const amountInCents = amount * 100;
  const date = new Date().toISOString().split('T')[0];

  await sql`INSERT INTO invoices (customer_id, amount, status, date) VALUES (${customerId}, ${amountInCents}, ${status}, ${date})`;

  // Revalidate the invoices page，需要更新一下 invoices 的缓存，保证用户看到最新的数据
  revalidatePath('/dashboard/invoices');
  redirect('/dashboard/invoices');
}

/**
 * 这个 schema 和 createInvoice 的 schema 是一样的，但是它不包含 id 和 date 字段，因为 id 和 date 字段是自动生成的。
 */
const UpdateInvoice = FormSchema.omit({ id: true, date: true });

export async function updateInvoice(id: string, formData: FormData) {
  const { customerId, amount, status } = UpdateInvoice.parse({
    customerId: formData.get('customerId'),
    amount: formData.get('amount'),
    status: formData.get('status'),
  });

  const amountInCents = amount * 100;
  await sql`UPDATE invoices SET customer_id = ${customerId}, amount = ${amountInCents}, status = ${status} WHERE id = ${id}`;
  revalidatePath('/dashboard/invoices');
  redirect('/dashboard/invoices');
}

export async function deleteInvoice(id: string) {
  throw new Error('Failed to delete invoice');

  await sql`DELETE FROM invoices WHERE id = ${id}`;
  revalidatePath('/dashboard/invoices');
}
